version: "3"
services:
  web:
    image: openresty/openresty:buster-fat #nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d #nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
  backend:
    build: ./backend/
    ports:
      - "8080:8080"
  caller:
    image: tutum/curl
    depends_on:
      - web
    entrypoint: ["curl", "-sq", "-H Host:test", "web:80/"]
